<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wro_actual">

  <xacro:include filename="$(find robot_system)/urdf/wro.materials.xacro" />
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="4.0" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.127" /> <!-- 12.70 cm -->
  <xacro:property name="base_length" value="0.200" /> <!-- 20.00 cm -->
  <xacro:property name="base_height" value="0.050" /> <!-- 6.00 cm -->
  <xacro:property name="wheelbase" value="0.165" /> <!-- 21.50 cm -->
  <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.020" /> <!-- 2.00 cm -->
  <xacro:property name="wheel_radius" value="0.025" /> <!-- 2.50 cm -->
  
  <!-- LIDAR Dimensions -->
  <xacro:property name="lidar_length" value="0.0556"/>  <!-- 55.6 mm -->
  <xacro:property name="lidar_width" value="0.0556"/>   <!-- 55.6 mm -->
  <xacro:property name="lidar_height" value="0.0413"/>  <!-- 41.3 mm -->

  <xacro:property name="lidar_mass" value="0.17"/>
  <xacro:property name="lidar_inertia_ixx" value="0.0001926666667"/>
  <xacro:property name="lidar_inertia_iyy" value="0.0001224141667"/>
  <xacro:property name="lidar_inertia_izz" value="0.0002130808333"/>

  <!-- LIDAR Position Relative to Chassis -->
  <xacro:property name="lidar_pos_x" value="0.072"/> <!-- 9.5 cm forward -->
  <xacro:property name="lidar_pos_y" value="0.0"/>    <!-- Centered in y-axis -->
  <xacro:property name="lidar_pos_z" value="0.0456"/>   <!-- 7.5 cm above the base -->

  <xacro:property name="camera_length" value="0.021"/>   <!-- 25 mm -->
  <xacro:property name="camera_width" value="0.03"/>    <!-- 24 mm -->
  <xacro:property name="camera_height" value="0.03"/>   <!-- 9 mm -->
  <xacro:property name="camera_pos_x" value="-0.002"/>   <!-- 8.7 cm forward -->
  <xacro:property name="camera_pos_y" value="0.0"/>      <!-- Centered in y-axis -->
  <xacro:property name="camera_pos_z" value="0.1106"/>     <!-- 18.0 cm above base -->
  <xacro:property name="camera_pitch" value="0.262"/>  <!-- 12 degrees in radians -->
  <xacro:property name="camera_yaw" value="-0.05"/>  <!-- 12 degrees in radians -->

  <!-- Base Link -->
  <link name="base_link" />

  <!-- Chassis -->
  <link name="chassis_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0.025 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.2"/>
  </joint>

  <!-- Rear Wheels -->

  <!-- Rear Right Wheel -->
  <link name="rear_right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-${wheelbase/2} -${base_width/2} 0.018" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" velocity="100.0"/>
    <dynamics damping="0.2"/>
  </joint>

  <!-- Rear Left Wheel -->
  <link name="rear_left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-${wheelbase/2} ${base_width/2} 0.018" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" velocity="100.0"/>
    <dynamics damping="0.2"/>
  </joint>

  <!-- Front Wheels -->

  <!-- Front Right Wheel -->
  <link name="front_right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="front_right_wheel_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheelbase/2} -${base_width/2} 0.018" rpy="0 0 ${PI/2}"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
    <dynamics damping="0.2"/>
  </joint>

  <!-- Front Left Wheel -->
  <link name="front_left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="front_left_wheel_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheelbase/2} ${base_width/2} 0.018" rpy="0 0 ${PI/2}"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
    <dynamics damping="0.2"/>
  </joint>


  <!-- LIDAR Link -->
  <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${lidar_mass}"/>
      <inertia
        ixx="${lidar_inertia_ixx}" ixy="0" ixz="0"
        iyy="${lidar_inertia_iyy}" iyz="0"
        izz="${lidar_inertia_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- LIDAR Joint -->
  <joint name="lidar_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="lidar_link"/>
    <origin xyz="${lidar_pos_x} ${lidar_pos_y} ${lidar_pos_z}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Link -->
  <link name="camera_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>  <!-- Adjust mass as necessary -->
      <inertia
        ixx="0.00002" ixy="0" ixz="0"
        iyy="0.00002" iyz="0"
        izz="0.00002"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Camera Joint -->
  <joint name="camera_joint" type="fixed">
    <parent link="lidar_link"/>
    <child link="camera_link"/>
    <!-- Position and orientation for the camera relative to the lidar -->
    <origin xyz="${camera_pos_x} ${camera_pos_y} ${camera_pos_z}" rpy="0 ${camera_pitch} ${camera_yaw}"/>
  </joint>
</robot>